### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [Almeida100/Merge-Selected-Features#1]
# Problem

In terms of code, what is the major difference between the QGIS code and your plugin? I would like to suggest that you do a PR to QGIS with your changes so that they could benefit a large user base. If this part of the code base has already been ported to C++ and you do not have experience with this you can open an issue report in QGIS with a link to your repo and hope an experienced C++ developer will pick this up

**Comment by Almeida100** [comment]
This is a (completely) different approach to merge selected features on a polygon vector layer.
I’ll be very satisfied to see this processing plugin ported to C++.
Meanwhile, I also would like to see it published as a processing plugin, because this plugin can be useful for QGis users.

**Comment by NyakudyaA** [comment]
> This is a (completely) different approach to merge selected features on a polygon vector layer.
> 
> I’ll be very satisfied to see this processing plugin ported to C++.
> 
> Meanwhile, I also would like to see it published as a processing plugin, because this plugin can be useful for QGis users.
> 
> 

@Almeida100 thanks for your response but I think it is important for you to start this conversation in the QGIS developer user group so that you can get feedback on what is the best way forward and maybe one of the developers could port the plugin. 

Alternatively as I said you an open an feature  request on GitHub mentioning the different approaches and how you have done so.

After that I can approve this plugin because I feel this is an important part of geoprocessing

**Comment by Almeida100** [comment]
I'm very sorry, but I don't have time for this.
Many thanks, anyway.

**Comment by Almeida100** [comment]
Since this plugin has already been published, and there have been many downloads, without further reporting of problems, I will close the issue.
